# Generated by Django 5.1.5 on 2025-04-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('other', 'Other')], max_length=20)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_age', models.CharField(max_length=100)),
                ('pet_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('pet_weight', models.IntegerField()),
                ('pet_height', models.IntegerField()),
                ('pet_medical_condition', models.TextField()),
                ('pet_vaccination_status', models.TextField()),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('package_type', models.CharField(choices=[('friendlypack', 'Friendlypack'), ('exclusivepack', 'Exclusivepack'), ('familypack', 'Familypack'), ('customizedpack', 'Customizepack')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to='gromming.servicetype')),
            ],
        ),
    ]
