# Generated by Django 5.1.5 on 2025-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gromming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizepackage',
            name='pet_height',
            field=models.FloatField(),
        ),
    ]
